[atom]
id = "horizons-rs"
version = "0.1.0"
system = true
propagate = true
src = "rust-atom"

[std]
features = ["lib"]

[backend.nix]
fetcher = "flake-lock"

[fetch.src]
name = "horizons-rs"
type = "src"
